x-nginx: &nginx-latest
  image: nginx:latest

x-volumes:
  - &app-vol "../:/app"

version: '3'
services:
  php1:
    build: .
    volumes:
      - *app-vol
      - ./node1.ini:/app/node.ini
      - ./accountstore1.json:/app/accountstore.json

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: secret
      CC_DATABASES: cc-test-1 cc-test-2 cc-test-3 # space-separated list of databases to be created
    volumes:
      - ./init-all-dbs.sh:/docker-entrypoint-initdb.d/init-all-dbs.sh # creates databases
      - ./install.sql:/custom-init-scripts/install.sql # used to bootstrap every database

  cc-test-1:
    <<: *nginx-latest
    ports:
      - 8001:80
    volumes:
      - "./nginx1.conf:/etc/nginx/conf.d/default.conf"
      - *app-vol
      - ./node1.ini:/app/node.ini
      - ./accountstore1.json:/app/accountstore.json
