version: '3'
services:
  php1:
    build: .
    volumes:
      - "../:/app"
      - ./node.ini:/app/node.ini
      - ./accountstore.json:/app/accountstore.json
      - ./workflows.json:/app/workflows.json
    extra_hosts:
      host.docker.internal: host-gateway

  cc-server:
    image: nginx:1.24.0
    ports:
      - 8000:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "../:/app"
      - ./node.ini:/app/node.ini
      - ./accountstore.json:/app/accountstore.json
      - ./workflows.json:/app/workflows.json
    extra_hosts:
      host.docker.internal: host-gateway

  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cc-server
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - ../vendor/credit-commons/cc-node/install.sql:/docker-entrypoint-initdb.d/install.sql # used to bootstrap database
